{"name": "test_mul[failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -27 == 27", "trace": "self = <testing.test_calc.TestCalc object at 0x000002233EBCB700>, get_calc = <python_code.calc.Calculator object at 0x000002233EB11100>, get_datas4 = [-3, 9, 27]\n\n    @allure.story(\"测试乘法\")\n    @pytest.mark.run(order=3)\n    # 乘法的测试用例\n    def test_mul(self, get_calc, get_datas4):\n        with allure.step(\"计算两数相乘的结果\"):\n            result = get_calc.mul(get_datas4[0], get_datas4[1])\n    \n        # 可以使用isinstance来判断类型,判断result是浮点数，作保留两位小数的处理\n        if isinstance(result, float):\n            result = round(result, 2)\n        # 断言，得到结果后需要写断言\n>       assert result == get_datas4[2]\nE       assert -27 == 27\n\ntest_calc.py:166: AssertionError"}, "steps": [{"name": "计算两数相乘的结果", "status": "passed", "start": 1612436648753, "stop": 1612436648753}], "attachments": [{"name": "stdout", "source": "0ce9e159-c874-4da5-9536-4c8fe0703ca9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas4", "value": "[-3, 9, 27]"}], "start": 1612436648753, "stop": 1612436648754, "uuid": "4c3412e7-4d35-4465-ad69-73fc4fbff9f2", "historyId": "b51952daefdbc0d8e61623f5f10e7fe9", "testCaseId": "463eb02829151a13063664521f3c4534", "fullName": "test_calc.TestCalc#test_mul", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "测试乘法"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-2I60K4O"}, {"name": "thread", "value": "14972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}